/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/ws/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["issueTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMine"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["markRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["markAll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listByStatus"];
        put?: never;
        post: operations["createAlert"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/{alertId}/votes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["vote"];
        delete: operations["removeVote"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updatePreferences"];
        trace?: never;
    };
    "/api/v1/alerts/{id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["resolve"];
        trace?: never;
    };
    "/api/v1/admin/users/{id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["changeRole"];
        trace?: never;
    };
    "/api/v1/admin/users/{id}/enabled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["setEnabled"];
        trace?: never;
    };
    "/api/v1/uploads/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["serve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/unread": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["unread"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/unread/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["unreadCount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/{alertId}/votes/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/{alertId}/votes/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMyVote"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/nearby": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active alerts within a radius, optionally filtered and newer than `since` */
        get: operations["getNearbyAlerts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        WebSocketTicketResponse: {
            ticket?: string;
            /** Format: date-time */
            expiresAt?: string;
        };
        /** @description Request body for creating an alert subscription */
        SubscriptionRequest: {
            /**
             * @description Alert type to subscribe to
             * @example GAS_LEAK
             * @enum {string}
             */
            alertType: "CRIME" | "FIRE" | "ACCIDENT" | "MEDICAL_EMERGENCY" | "NATURAL_DISASTER" | "SUSPICIOUS_ACTIVITY" | "TRAFFIC" | "HAZARD" | "MISSING_PERSON" | "OTHER";
            /**
             * Format: double
             * @description Center latitude of the watch area
             * @example 40.7128
             */
            latitude: number;
            /**
             * Format: double
             * @description Center longitude of the watch area
             * @example -74.006
             */
            longitude: number;
            /**
             * Format: double
             * @description Radius in kilometres around the center point
             * @example 5
             */
            radiusKm: number;
        };
        /** @description Active subscription details */
        SubscriptionResponse: {
            /**
             * Format: uuid
             * @description Subscription identifier
             */
            id?: string;
            /**
             * Format: uuid
             * @description Owner of the subscription
             */
            userId?: string;
            /**
             * @description Subscribed alert type
             * @enum {string}
             */
            alertType?: "CRIME" | "FIRE" | "ACCIDENT" | "MEDICAL_EMERGENCY" | "NATURAL_DISASTER" | "SUSPICIOUS_ACTIVITY" | "TRAFFIC" | "HAZARD" | "MISSING_PERSON" | "OTHER";
            /**
             * Format: double
             * @description Center latitude
             */
            latitude?: number;
            /**
             * Format: double
             * @description Center longitude
             */
            longitude?: number;
            /**
             * Format: double
             * @description Watch radius in km
             */
            radiusKm?: number;
            /** @description Whether the subscription is active */
            active?: boolean;
            /**
             * Format: date-time
             * @description Creation timestamp
             */
            createdAt?: string;
        };
        /** @description A user notification (vote event or milestone) */
        NotificationResponse: {
            /**
             * Format: uuid
             * @description Notification identifier
             */
            id?: string;
            /**
             * Format: uuid
             * @description ID of the user who receives this notification
             */
            recipientId?: string;
            /**
             * @description What triggered the notification
             * @example VOTE
             * @enum {string}
             */
            type?: "ALERT_UPVOTED" | "ALERT_DOWNVOTED" | "ALERT_CONFIRMED" | "ALERT_MILESTONE" | "ALERT_RESOLVED";
            /**
             * @description Short notification title
             * @example New vote on your alert
             */
            title?: string;
            /** @description Notification body text */
            message?: string;
            /**
             * Format: uuid
             * @description Alert that triggered the notification; may be null
             */
            relatedAlertId?: string;
            /**
             * Format: uuid
             * @description User who caused the notification; may be null
             */
            triggeredByUserId?: string;
            /** @description Whether the notification has been read by the recipient */
            read?: boolean;
            /**
             * Format: date-time
             * @description Timestamp when the notification was created
             */
            createdAt?: string;
        };
        MessageResponse: {
            message?: string;
        };
        ResetPasswordRequest: {
            token: string;
            newPassword: string;
        };
        /** @description Request body for creating a new user account */
        RegisterRequest: {
            /**
             * Format: email
             * @description E-mail address (used as login)
             * @example alice@example.com
             */
            email: string;
            /**
             * @description Password — at least 10 characters, including a letter and a digit, and at most 72 UTF-8 bytes
             * @example s3cr3tP@ssphrase
             */
            password: string;
            /**
             * @description Public display name shown to other users
             * @example Alice
             */
            displayName: string;
        };
        /** @description Authentication tokens returned after a successful login or registration */
        AuthResponse: {
            /** @description Short-lived JWT access token — include in Authorization: Bearer header */
            accessToken?: string;
            /** @description Single-use refresh token used to obtain a new pair */
            refreshToken?: string;
            /**
             * Format: int64
             * @description Access-token validity in milliseconds
             * @example 86400000
             */
            expiresIn?: number;
            /** @description Basic profile of the authenticated user */
            user?: components["schemas"]["UserResponse"];
        };
        /** @description Public profile of a user */
        UserResponse: {
            /**
             * Format: uuid
             * @description Stable user identifier
             */
            id?: string;
            /**
             * @description E-mail address
             * @example alice@example.com
             */
            email?: string;
            /**
             * @description Display name shown to other users
             * @example Alice
             */
            displayName?: string;
            /**
             * @description Assigned role
             * @example USER
             * @enum {string}
             */
            role?: "USER" | "MODERATOR" | "ADMIN";
            /** @description Whether the email address has been verified */
            emailVerified?: boolean;
            /** @description Whether the account may sign in — an admin can switch this off */
            enabled?: boolean;
            /**
             * Format: int32
             * @description Configured notification radius in kilometres
             * @example 5
             */
            notificationRadiusKm?: number;
        };
        RefreshTokenRequest: {
            refreshToken: string;
        };
        RefreshTokenResponse: {
            accessToken?: string;
            refreshToken?: string;
            /** Format: int64 */
            expiresIn?: number;
        };
        /** @description Credentials for logging in */
        LoginRequest: {
            /**
             * Format: email
             * @description Registered e-mail address
             * @example alice@example.com
             */
            email: string;
            /**
             * @description Account password
             * @example s3cr3tP@ss
             */
            password: string;
        };
        ForgotPasswordRequest: {
            /** Format: email */
            email: string;
        };
        /** @description Request body for creating a new safety alert */
        CreateAlertRequest: {
            /**
             * @description Short title of the alert
             * @example Gas leak on Main St
             */
            title: string;
            /**
             * @description Detailed description of the alert
             * @example Strong smell of gas near intersection
             */
            description: string;
            /**
             * @description Category of the alert
             * @example GAS_LEAK
             * @enum {string}
             */
            type: "CRIME" | "FIRE" | "ACCIDENT" | "MEDICAL_EMERGENCY" | "NATURAL_DISASTER" | "SUSPICIOUS_ACTIVITY" | "TRAFFIC" | "HAZARD" | "MISSING_PERSON" | "OTHER";
            /**
             * @description Severity level
             * @example HIGH
             * @enum {string}
             */
            severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            /**
             * Format: double
             * @description WGS-84 latitude of the incident
             * @example 40.7128
             */
            latitude: number;
            /**
             * Format: double
             * @description WGS-84 longitude of the incident
             * @example -74.006
             */
            longitude: number;
            /**
             * @description URL of an uploaded photo for this alert
             * @example /api/v1/uploads/uuid.jpg
             */
            photoUrl?: string;
        };
        /** @description Alert details returned by the API */
        AlertResponse: {
            /**
             * Format: uuid
             * @description Unique identifier of the alert
             */
            id?: string;
            /** @description Short title */
            title?: string;
            /** @description Full description */
            description?: string;
            /**
             * @description Alert category
             * @enum {string}
             */
            type?: "CRIME" | "FIRE" | "ACCIDENT" | "MEDICAL_EMERGENCY" | "NATURAL_DISASTER" | "SUSPICIOUS_ACTIVITY" | "TRAFFIC" | "HAZARD" | "MISSING_PERSON" | "OTHER";
            /**
             * @description Severity level
             * @enum {string}
             */
            severity?: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            /**
             * Format: double
             * @description Latitude of the incident location
             * @example 40.7128
             */
            latitude?: number;
            /**
             * Format: double
             * @description Longitude of the incident location
             * @example -74.006
             */
            longitude?: number;
            /**
             * Format: date-time
             * @description Timestamp when the alert was created
             */
            createdAt?: string;
            /**
             * @description Current lifecycle status
             * @enum {string}
             */
            status?: "ACTIVE" | "RESOLVED";
            /**
             * Format: uuid
             * @description ID of the user who reported the alert
             */
            reportedBy?: string;
            /**
             * Format: int32
             * @description Number of upvotes
             */
            upvoteCount?: number;
            /**
             * Format: int32
             * @description Number of downvotes
             */
            downvoteCount?: number;
            /**
             * Format: int32
             * @description Number of confirmations
             */
            confirmationCount?: number;
            /**
             * Format: int32
             * @description Credibility score as computed by the voting service
             */
            credibilityScore?: number;
            /**
             * Format: date-time
             * @description Timestamp when the alert was resolved; null if still active
             */
            resolvedAt?: string;
            /** @description URL of the uploaded photo, if any */
            photoUrl?: string;
        };
        /** @description Request body for casting a vote on an alert */
        VoteRequest: {
            /**
             * @description Type of vote to cast
             * @example UPVOTE
             * @enum {string}
             */
            voteType: "UPVOTE" | "DOWNVOTE" | "CONFIRM";
        };
        /** @description The recorded vote and the resulting tallies */
        VoteResponse: {
            /**
             * Format: uuid
             * @description Vote identifier
             */
            id?: string;
            /**
             * Format: uuid
             * @description ID of the alert that was voted on
             */
            alertId?: string;
            /**
             * @description Type of vote
             * @enum {string}
             */
            voteType?: "UPVOTE" | "DOWNVOTE" | "CONFIRM";
            /**
             * Format: date-time
             * @description When the vote was recorded
             */
            createdAt?: string;
            /** @description Tallies after this vote */
            stats?: components["schemas"]["VoteStatsResponse"];
        };
        /** @description Aggregate vote statistics for an alert */
        VoteStatsResponse: {
            /**
             * Format: int32
             * @description Number of upvotes
             */
            upvotes?: number;
            /**
             * Format: int32
             * @description Number of downvotes
             */
            downvotes?: number;
            /**
             * Format: int32
             * @description Number of confirmations
             */
            confirmations?: number;
            /**
             * Format: int32
             * @description Credibility score as computed by the voting service
             */
            credibilityScore?: number;
        };
        /** @description Request body for updating notification preferences */
        UpdateUserPreferencesRequest: {
            /**
             * Format: int32
             * @description Allowed radius preset in kilometres
             * @example 10
             */
            notificationRadiusKm: number;
            /**
             * Format: double
             * @description Latest known latitude
             * @example 42.3601
             */
            lastKnownLat?: number;
            /**
             * Format: double
             * @description Latest known longitude
             * @example -71.0589
             */
            lastKnownLng?: number;
        };
        /** @description Assigns a role to an account */
        ChangeRoleRequest: {
            /**
             * @description The role to assign
             * @example MODERATOR
             * @enum {string}
             */
            role: "USER" | "MODERATOR" | "ADMIN";
        };
        /** @description Enables or disables an account */
        SetEnabledRequest: {
            /**
             * @description False disables the account and invalidates its sessions immediately
             * @example false
             */
            enabled: boolean;
        };
        /** @description Indicates whether the current user has voted on an alert */
        UserVoteResponse: {
            /** @description true if the authenticated user has an active vote */
            hasVoted?: boolean;
            /**
             * @description The vote type, or null if hasVoted is false
             * @enum {string}
             */
            voteType?: "UPVOTE" | "DOWNVOTE" | "CONFIRM";
        };
        /** @description Active alerts near a point, capped at `limit` */
        NearbyAlertsResponse: {
            /** @description Matching alerts, newest first */
            alerts?: components["schemas"]["AlertResponse"][];
            /**
             * Format: int32
             * @description Number of alerts in this response
             * @example 42
             */
            count?: number;
            /**
             * Format: int32
             * @description The cap that was applied
             * @example 100
             */
            limit?: number;
            /**
             * @description True when the cap was reached and older matches were dropped. Narrow the radius or filter by type/severity to see them.
             * @example false
             */
            truncated?: boolean;
        };
        /** @description One page of accounts, with the total so a caller knows there are more */
        UserPageResponse: {
            users?: components["schemas"]["UserResponse"][];
            /** Format: int64 */
            total?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    issueTicket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WebSocketTicketResponse"];
                };
            };
        };
    };
    upload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    listMine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SubscriptionResponse"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscriptionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SubscriptionResponse"];
                };
            };
        };
    };
    markRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NotificationResponse"];
                };
            };
        };
    };
    markAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    verifyEmail: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RefreshTokenResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    listByStatus: {
        parameters: {
            query?: {
                status?: "ACTIVE" | "RESOLVED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AlertResponse"][];
                };
            };
        };
    };
    createAlert: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAlertRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AlertResponse"];
                };
            };
        };
    };
    vote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alertId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoteRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VoteResponse"];
                };
            };
        };
    };
    removeVote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alertId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VoteStatsResponse"];
                };
            };
        };
    };
    updatePreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserPreferencesRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    resolve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AlertResponse"];
                };
            };
        };
    };
    changeRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeRoleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    setEnabled: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetEnabledRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    serve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NotificationResponse"][];
                };
            };
        };
    };
    unread: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NotificationResponse"][];
                };
            };
        };
    };
    unreadCount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: number;
                    };
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AlertResponse"];
                };
            };
        };
    };
    getStats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alertId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VoteStatsResponse"];
                };
            };
        };
    };
    getMyVote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alertId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserVoteResponse"];
                };
            };
        };
    };
    getNearbyAlerts: {
        parameters: {
            query: {
                latitude: number;
                longitude: number;
                radiusKm?: number;
                since?: string;
                type?: "CRIME" | "FIRE" | "ACCIDENT" | "MEDICAL_EMERGENCY" | "NATURAL_DISASTER" | "SUSPICIOUS_ACTIVITY" | "TRAFFIC" | "HAZARD" | "MISSING_PERSON" | "OTHER";
                severity?: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NearbyAlertsResponse"];
                };
            };
        };
    };
    listUsers: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserPageResponse"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
